### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by rdaly525** [rdaly525/MetaMapper#27]
- [ ] Figure out a plan to pass semantic information from Halide to CoreIR (What is Data, what is Valid, what is reset)
- [ ] There is an issue with getting into random states after configuration. Need to replace control registers to reset-able registers.
- [ ] Write a plan for how to specify pipelining/retiming
